### GET User by ID
GET http://localhost:3500/api/user/0 HTTP/1.1

### GET Users
GET http://localhost:3500/api/user HTTP/1.1

### POST User
POST http://localhost:3500/api/user HTTP/1.1
Content-Type: application/json

{
	"id_usuario":2,
	"nome":"gabriel",
	"senha":"1234",
	"url_imagem":"https://i.pinimg.com/736x/94/1d/71/941d71a2241c764419aafc390329f81c.jpg",
	"exp":1000,
	"nivel":10,
	"tarefas": [3, 4]
}

### PUT User by ID
PUT http://localhost:3500/api/user/2 HTTP/1.1
Content-Type: application/json

{
	"id_usuario":1,
	"nome":"carlito",
	"senha":"1234",
	"url_imagem":"https://i.pinimg.com/736x/94/1d/71/941d71a2241c764419aafc390329f81c.jpg",
	"exp":900,
	"nivel":9,
	"tarefas": [3, 4]
}

### DELETE User by ID
DELETE http://localhost:3500/api/user/1 HTTP/1.1

### GET Tarefa by ID
GET http://localhost:3500/api/tarefa/0 HTTP/1.1

### GET Tarefas
GET http://localhost:3500/api/tarefa HTTP/1.1

### POST Tarefa
POST http://localhost:3500/api/tarefa HTTP/1.1
Content-Type: application/json

{
  "id_tarefa":1,
	"nome": "Apresentação mutcho doida",
	"descricao": "Apresentaaaaassãuuuu",
	"dificuldade": 3,
	"habito": false,
	"frequencia": "semanal"
}

### PUT Tarefa by ID
PUT http://localhost:3500/api/tarefa/1 HTTP/1.1
Content-Type: application/json

{
  "id_tarefa":1,
	"nome": "bem legal",
	"descricao": "ihuuuu",
	"dificuldade": 3,
	"habito": false,
	"frequencia": "semanal"
}

### DELETE Tarefa by ID
DELETE http://localhost:3500/api/tarefa/1 HTTP/1.1